version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - .:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000